from django.urls import path
from . import views

app_name = 'orcamentos'

urlpatterns = [
    path('', views.lista_orcamentos, name='lista_orcamentos'),
    path('novo/', views.novo_orcamento, name='novo_orcamento'),
    path('gerar-catalogo-pdf/', views.gerar_catalogo_pdf_view, name='gerar_catalogo_pdf'),
    path('<int:orcamento_id>/', views.detalhes_orcamento, name='detalhes_orcamento'),
    path('<int:orcamento_id>/editar/', views.editar_orcamento, name='editar_orcamento'),
    path('<int:orcamento_id>/excluir/', views.excluir_orcamento, name='excluir_orcamento'),
    path('<int:orcamento_id>/baixar-pdf/', views.baixar_pdf, name='baixar_pdf'),
    path('<int:orcamento_id>/baixar-png/', views.baixar_png, name='baixar_png'),
    path('<int:orcamento_id>/checklist-pdf/', views.gerar_checklist_pdf_view, name='gerar_checklist_pdf'),
    path('<int:orcamento_id>/recibo-pdf/', views.gerar_recibo_pdf_view, name='gerar_recibo_pdf'),
    path('<int:orcamento_id>/alterar-status/', views.alterar_status, name='alterar_status'),
    path('<int:orcamento_id>/registrar-pagamento/', views.registrar_pagamento, name='registrar_pagamento'),
    path('clientes/novo/', views.novo_cliente, name='adicionar_cliente'),
    path('clientes/', views.lista_clientes, name='lista_clientes'),
    path('clientes/<int:cliente_id>/', views.cliente_detalhes, name='cliente_detalhes'),
    path('clientes/<int:cliente_id>/excluir/', views.excluir_cliente, name='excluir_cliente'),
    path('agendamentos/', views.agendamentos, name='agendamentos'),
    path('agendamentos/resumo-festas/', views.resumo_festas, name='resumo_festas'),
    path('agendamentos/conflitos/', views.conflitos_agenda, name='conflitos_agenda'),
    path('agendamentos/disponibilidade/', views.disponibilidade_dia, name='disponibilidade_dia'),
    path('agendamentos/conflitos/verificar/', views.verificar_conflito, name='verificar_conflito'),
    path('agendamentos/<int:orcamento_id>/concluir/', views.concluir_agendamento, name='concluir_agendamento'),
    path('agendamentos/<int:orcamento_id>/reabrir/', views.reabrir_agendamento, name='reabrir_agendamento'),
    path('itens/novo/', views.novo_item, name='adicionar_item'),
    path('itens/', views.lista_itens, name='lista_itens'),
    path('itens/editar/<int:item_id>/', views.editar_item, name='editar_item'),
    path('itens/excluir/<int:item_id>/', views.excluir_item, name='excluir_item'),
    path('itens/<int:item_id>/foto/', views.foto_item, name='foto_item'),
    path('itens/<int:item_id>/inflavel/', views.alternar_inflavel, name='alternar_inflavel'),
    path('catalogo/links/', views.links_catalogo, name='links_catalogo'),
    path('pedidos/', views.pre_orcamentos, name='pre_orcamentos'),
    path('pedidos/<int:pre_id>/acao/', views.pre_orcamento_acao, name='pre_orcamento_acao'),
    path('enviar-notificacao-whatsapp/<int:orcamento_id>/', views.enviar_notificacao_whatsapp, name='enviar_notificacao_whatsapp'),
]