# Generated by Django 5.2.5 on 2025-09-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cor_acento',
            field=models.CharField(default='#FF6B6B', max_length=7, verbose_name='Cor de Acento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_principal',
            field=models.CharField(default='#2463EB', max_length=7, verbose_name='Cor Principal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_secundaria',
            field=models.CharField(default='#4ECDC4', max_length=7, verbose_name='Cor Secundária'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tema_escuro',
            field=models.BooleanField(default=False, verbose_name='Tema Escuro'),
        ),
    ]
