# Generated by Django 5.2.5 on 2026-09-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_empresa_cidade_empresa_instagram_empresa_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='assinatura',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/assinaturas/', verbose_name='Assinatura'),
        ),
    ]
