# Generated by Django 5.2.5 on 2026-10-01 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_empresa_assinatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemArmazenada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.BinaryField()),
                ('tipo', models.CharField(default='image/jpeg', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagem armazenada',
                'verbose_name_plural': 'Imagens armazenadas',
            },
        ),
        migrations.AlterField(
            model_name='empresa',
            name='assinatura',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/assinaturas/', verbose_name='Assinatura (arquivo antigo)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo (arquivo antigo)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='assinatura_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.imagemarmazenada', verbose_name='Assinatura'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.imagemarmazenada', verbose_name='Logo'),
        ),
    ]
