# Generated by Django 5.2.5 on 2026-10-01 02:19

import mimetypes

from django.db import migrations


def copiar_para_banco(apps, schema_editor):
    """
    Copia a logo e a assinatura que estavam como arquivo em media/ para a
    tabela ImagemArmazenada. Os arquivos e as colunas antigas não são
    apagados. Se o arquivo não existir neste servidor, só avisa e segue.
    """
    Empresa = apps.get_model('accounts', 'Empresa')
    ImagemArmazenada = apps.get_model('accounts', 'ImagemArmazenada')

    for empresa in Empresa.objects.all():
        for campo_arquivo, campo_img in (('logo', 'logo_img'), ('assinatura', 'assinatura_img')):
            arquivo = getattr(empresa, campo_arquivo)
            if not arquivo or getattr(empresa, f'{campo_img}_id'):
                continue
            try:
                with arquivo.open('rb') as f:
                    dados = f.read()
            except (FileNotFoundError, OSError, ValueError):
                print(f"\n  Aviso: {campo_arquivo} da empresa '{empresa.nome}' ({arquivo.name}) não encontrada; "
                      f"envie de novo em Configurações da Empresa.")
                continue
            tipo = mimetypes.guess_type(arquivo.name)[0] or 'image/png'
            imagem = ImagemArmazenada.objects.create(dados=dados, tipo=tipo)
            setattr(empresa, campo_img, imagem)
            empresa.save(update_fields=[campo_img])
            print(f"\n  {campo_arquivo} da empresa '{empresa.nome}' copiada para o banco ({len(dados) // 1024} KB)")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_imagens_no_banco'),
    ]

    operations = [
        migrations.RunPython(copiar_para_banco, migrations.RunPython.noop),
    ]
