# Generated by Django 5.2.5 on 2025-11-01 20:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_empresa_cidade_empresa_instagram_empresa_whatsapp'),
        ('orcamentos', '0016_item_percentual_lucro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número do cliente')),
                ('nome_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do cliente')),
                ('mensagem', models.TextField(verbose_name='Conteúdo da mensagem')),
                ('direcao', models.CharField(choices=[('enviada', 'Enviada pelo sistema'), ('recebida', 'Recebida do cliente')], max_length=10, verbose_name='Direção')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('documento', 'Documento'), ('botao', 'Botão'), ('audio', 'Áudio'), ('outro', 'Outro')], default='texto', max_length=20, verbose_name='Tipo de mensagem')),
                ('origem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Origem do fluxo')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='mensagens/anexos/', verbose_name='Anexo')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='orcamentos.cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='accounts.empresa')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='orcamentos.orcamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Mensagem',
                'verbose_name_plural': 'Histórico de Mensagens',
                'ordering': ['-data_envio'],
            },
        ),
    ]
