# Generated by Django 5.2.5 on 2025-09-01 00:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='orcamento',
            options={'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AlterModelOptions(
            name='orcamentoitem',
            options={'verbose_name': 'Item do Orçamento', 'verbose_name_plural': 'Itens do Orçamento'},
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='data',
        ),
        migrations.RemoveField(
            model_name='orcamentoitem',
            name='desconto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('brinquedo', 'Brinquedo'), ('comida', 'Comida'), ('servico', 'Serviço'), ('outro', 'Outro')], default='brinquedo', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_evento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='orcamentos/pdf/'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='png',
            field=models.ImageField(blank=True, null=True, upload_to='orcamentos/png/'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='orcamentos.cliente'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orcamentoitem',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
