# Generated by Django 5.2.5 on 2025-09-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_alter_cliente_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
