# Generated by Django 5.2.5 on 2025-09-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_item_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoitem',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='orcamentoitem',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
