# Generated by Django 5.2.5 on 2025-09-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0004_orcamentoitem_desconto_orcamentoitem_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='hora_evento',
            field=models.TimeField(default='16:00'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='periodo_evento',
            field=models.CharField(default='3', max_length=1),
        ),
    ]
