# Generated by Django 5.2.5 on 2025-09-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0005_orcamento_hora_evento_orcamento_periodo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='tipo_evento',
            field=models.CharField(default='Aniversário', max_length=100),
        ),
    ]
