# Generated by Django 5.2.5 on 2025-09-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0008_cliente_observacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='endereco',
            field=models.TextField(default='sem'),
            preserve_default=False,
        ),
    ]
