# Generated by Django 5.2.5 on 2025-09-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0009_remove_cliente_email_remove_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
