# Generated by Django 5.2.5 on 2025-09-09 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orcamentos', '0010_orcamento_valor_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='emrpesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='accounts.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='accounts.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='accounts.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('brinquedo', 'Brinquedo'), ('comida', 'Comida'), ('servico', 'Serviço'), ('outro', 'Outro'), ('buffet', 'Buffet'), ('decoracao', 'Decoração'), ('personalizado', 'Personalizado')], default='brinquedo', max_length=20),
        ),
    ]
