# Generated by Django 5.2.5 on 2025-09-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0011_cliente_emrpesa_item_empresa_orcamento_criado_por_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='emrpesa',
            new_name='empesa',
        ),
    ]
