# Generated by Django 5.2.5 on 2025-09-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0012_rename_emrpesa_cliente_empesa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='empesa',
            new_name='empresa',
        ),
    ]
