# Generated by Django 5.2.5 on 2025-09-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0013_rename_empesa_cliente_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='custo_operacional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('brinquedo', 'Brinquedo'), ('comida', 'Comida'), ('servico', 'Serviço'), ('outro', 'Outro'), ('buffet', 'Buffet'), ('decoracao', 'Decoração'), ('personalizado', 'Personalizado'), ('buffet_personalizado', 'Buffet - Personalizado')], default='brinquedo', max_length=20),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído'), ('reagendar', 'Reagendado')], default='pendente', max_length=20),
        ),
    ]
