# Generated by Django 5.2.5 on 2025-09-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0014_orcamento_custo_operacional_alter_item_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='custo_fixo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='investimento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
