# Generated by Django 5.2.5 on 2025-09-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0015_item_custo_fixo_item_investimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='percentual_lucro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
