# Generated by Django 5.2.5 on 2026-10-01 01:23

import django.db.models.deletion
import orcamentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_empresa_assinatura'),
        ('orcamentos', '0017_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='exibir_catalogo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='itens/fotos/'),
        ),
        migrations.CreateModel(
            name='LinkCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=100)),
                ('token', models.CharField(default=orcamentos.models.gerar_token_catalogo, max_length=32, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('acessos', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_catalogo', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Link do Catálogo',
                'verbose_name_plural': 'Links do Catálogo',
            },
        ),
    ]
