# Generated by Django 5.2.5 on 2026-10-01 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_copiar_logo_assinatura_para_banco'),
        ('orcamentos', '0018_catalogo_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imagem',
        ),
        migrations.AddField(
            model_name='item',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.imagemarmazenada'),
        ),
    ]
