# Generated by Django 5.2.5 on 2026-10-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0019_foto_item_no_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inflavel',
            field=models.BooleanField(default=False),
        ),
    ]
