# Generated by Django 5.2.5 on 2026-10-01 03:12

import django.db.models.deletion
import orcamentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_copiar_logo_assinatura_para_banco'),
        ('orcamentos', '0020_item_inflavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=orcamentos.models.gerar_token_catalogo, max_length=32, unique=True)),
                ('tipo_evento', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('data_evento', models.DateField()),
                ('hora_evento', models.TimeField()),
                ('periodo_evento', models.CharField(default='3', max_length=1)),
                ('endereco', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('convertido', 'Orçamento gerado'), ('descartado', 'Descartado')], default='novo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('validade_ate', models.DateTimeField()),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_orcamentos', to='orcamentos.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_orcamentos', to='accounts.empresa')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_orcamentos', to='orcamentos.linkcatalogo')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orcamentos.orcamento')),
            ],
            options={
                'verbose_name': 'Pré-orçamento',
                'verbose_name_plural': 'Pré-orçamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PreOrcamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orcamentos.item')),
                ('pre_orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.preorcamento')),
            ],
        ),
    ]
