# Generated by Django 5.2.5 on 2026-10-01 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_copiar_logo_assinatura_para_banco'),
        ('orcamentos', '0022_item_preco_progressivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ConflitoVerificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura', models.CharField(max_length=500)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('verificado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflitos_verificados', to='accounts.empresa')),
                ('orcamento_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orcamentos.orcamento')),
                ('orcamento_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orcamentos.orcamento')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conflito verificado',
                'verbose_name_plural': 'Conflitos verificados',
                'unique_together': {('orcamento_a', 'orcamento_b')},
            },
        ),
    ]
